# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NmVhOTU0Y2E3MWYwMzJmZDAyZjMxNGJmN2NjOTQxYWQ4ODY5Y2E5OTUxMmNmMmJmODAyNzgwMzE1OWNmYzMyNTgxMWI0OTEyODRlMDEwMjFiNWQwZWQwYWIxYTc3ZDkyNTUxYTE0NzgxODMwZjgyNGM3YmRiMTA1OGQxZWU2OGE=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: playground
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: playground
    password:
